version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: mambaforge-latest
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    pre_install:
      - git update-index --assume-unchanged doc/conf.py ci/docs.yml
    post_create_environment:
      - pip install . --no-deps -vv

sphinx:
  configuration: doc/conf.py
  fail_on_warning: false

conda:
  environment: ci/docs.yml

formats: []
