{% set version = "2023.10.1" %}

package:
  name: 'uxarray'
  version: {{ version }}

build:
  noarch: python
  number: 0
  skip: True  # [py<3.5]

source:
  #git_rev: main   # For building from main branch for debugging purposes
  git_tag: v{{ version }}   # For building from a specific tag
  git_url: https://github.com/UXARRAY/uxarray
  #url: https://github.com/UXARRAY/uxarray/archive/v{{ version }}.tar.gz   # For building from a specific tag's tarball
  #path: . # for building from a local directory

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - xarray

test:
  source_files:
    - test
  requires:
    - dask
    - netcdf4
    - pytest
    - numba
    - numpy
    - scipy>=0.16
    - xarray
  imports:
    - uxarray
  commands:
    - conda info
    - conda list
    - python -m pytest

about:
#  home: https://
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Uxarray is a library of xarray based functions for visualizing unstructured grid datasets'

extra:
  recipe-maintainers:
    - P. Ullrich # https://github.com/paullric
    - O. Eroglu # https://github.com/erogluorhan
    - A. Zacharias # https://github.com/anissa111
    - R. Jain # https://github.com/rajeeja
    - J. Zhang # https://github.com/chengzhuzhang
    - R. Jacob # https://github.com/rljacob
