#!/usr/bin/env python
"""Write requirements pinning each dependency to its oldest supported release.

"Oldest supported" follows SPEC 0 (https://scientific-python.org/specs/spec-0000/):
the oldest minor release published within the last 24 months, raised to any
lower bound already declared in pyproject.toml.  Only releases that support
the oldest Python allowed by requires-python are considered.  Nothing here is stored or
needs bumping; the floors are recomputed from PyPI release dates on each run.

The output is meant for ``uv pip install --resolution lowest-direct``, which
installs exactly these floors (or the nearest release the resolver can make
consistent) while leaving transitive dependencies at their newest versions.

Usage: python ci/min-deps.py [--extras geo,viz] > requirements-min.txt
       python ci/min-deps.py --python-version  # oldest Python to test with
"""

import argparse
import datetime
import json
import sys
import tomllib
import urllib.request
from pathlib import Path

from packaging.requirements import Requirement
from packaging.specifiers import SpecifierSet
from packaging.version import Version

SUPPORT_WINDOW_YEARS = 2


def release_dates(name, python):
    """Return {Version: first upload date} for every final, unyanked release
    that supports the given Python version."""
    url = f"https://pypi.org/pypi/{name}/json"
    with urllib.request.urlopen(url, timeout=30) as response:
        releases = json.load(response)["releases"]

    dates = {}
    for version_str, files in releases.items():
        files = [f for f in files if not f.get("yanked")]
        if not files:
            continue
        try:
            version = Version(version_str)
        except ValueError:
            continue
        if version.is_prerelease or version.is_devrelease:
            continue
        if not any(
            python in SpecifierSet(f.get("requires_python") or "") for f in files
        ):
            continue
        dates[version] = min(
            datetime.date.fromisoformat(f["upload_time_iso_8601"][:10]) for f in files
        )
    return dates


def spec0_floor(dates, cutoff):
    """Return the first release of the oldest minor version released after
    cutoff, and the reason it was chosen.

    A minor version (e.g. numpy 2.1 or xarray 2024.10) is dated by its first
    release, so a recent patch release doesn't extend an old minor's support.
    If nothing is that recent, the newest minor version is the floor.
    """
    minors = {}
    for version in sorted(dates):
        minors.setdefault(version.release[:2], version)
    supported = [v for v in minors.values() if dates[v] >= cutoff]
    if supported:
        return min(supported), "SPEC 0"
    return max(minors.values()), "newest minor"


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--extras",
        default="geo,viz",
        help="comma-separated optional-dependency groups to include",
    )
    parser.add_argument(
        "--pyproject",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "pyproject.toml",
    )
    parser.add_argument(
        "--python-version",
        action="store_true",
        help="print the oldest Python allowed by requires-python and exit",
    )
    args = parser.parse_args()

    project = tomllib.loads(args.pyproject.read_text())["project"]
    python = min(
        Version(s.version)
        for s in SpecifierSet(project["requires-python"])
        if s.operator == ">="
    )
    if args.python_version:
        print(python)
        return

    requirements = list(project["dependencies"])
    for extra in filter(None, args.extras.split(",")):
        requirements += project["optional-dependencies"][extra]

    today = datetime.datetime.now(datetime.UTC).date()  # PyPI upload times are UTC
    cutoff = today.replace(year=today.year - SUPPORT_WINDOW_YEARS)

    print(f"# Oldest dependencies supporting Python {python} as of {today}")
    print(f"# (SPEC 0 cutoff {cutoff}).")
    print("# Generated by ci/min-deps.py; do not edit.")
    seen = {}
    for line in requirements:
        req = Requirement(line)
        # A package listed in more than one group (e.g. cartopy) must satisfy
        # every declared specifier.
        if req.name in seen:
            seen[req.name].specifier &= req.specifier
            seen[req.name].extras |= req.extras
        else:
            seen[req.name] = req

    for req in seen.values():
        dates = release_dates(req.name, python)
        floor, reason = spec0_floor(dates, cutoff)
        allowed = sorted(v for v in dates if v >= floor and v in req.specifier)
        if not allowed:
            sys.exit(
                f"No release of {req.name} satisfies {req.specifier} and >={floor}"
            )
        oldest = allowed[0]
        extras = f"[{','.join(sorted(req.extras))}]" if req.extras else ""
        specifiers = ",".join(
            [f">={oldest}"] + [str(s) for s in req.specifier if s.operator != ">="]
        )
        if oldest != floor:
            reason = "declared bound"
        print(f"{req.name}{extras}{specifiers}  # {reason}, released {dates[oldest]}")


if __name__ == "__main__":
    main()
