name: uxarray_build
channels:
  - conda-forge
dependencies:
  - netcdf4
  - pathlib
  - python
  - pytest
  - pytest-cov
  - pip
  - pip:
    - git+https://github.com/pydata/xarray.git
    - git+https://github.com/dask/dask.git
