name: uxarray_upstream_build
channels:
  - conda-forge
dependencies:
  - matplotlib-base
  - netcdf4
  - numba
  - numpy
  - pathlib
  - pytest
  - pytest-cov
  - scipy
  - shapely
  - spatialpandas
  - pip:
    - antimeridian
