name: CI
on:
  pull_request:
  workflow_dispatch:
  schedule:
     - cron: '0 0 * * *' # Daily “At 00:00”

jobs:
  test:
    # if: |
    #   github.repository == 'UXARRAY/uxarray'
    name: Python (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    env:
      MPLBACKEND: Agg
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [ "3.11", "3.12", "3.13"]
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.13.1
        with:
          access_token: ${{ github.token }}

      - name: checkout
        uses: actions/checkout@v7
        with:
          token: ${{ github.token }}

      - name: conda_setup (x64)
        uses: conda-incubator/setup-miniconda@v4
        if: matrix.os != 'macos-14'
        with:
          activate-environment: uxarray_build
          channel-priority: strict
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          environment-file: ci/environment.yml
          miniforge-variant: Miniforge3
          miniforge-version: latest

      - name: conda_setup (ARM64)
        uses: conda-incubator/setup-miniconda@v4
        if: matrix.os == 'macos-14'
        with:
          activate-environment: uxarray_build
          channel-priority: strict
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          environment-file: ci/environment.yml
          installer-url: https://github.com/conda-forge/miniforge/releases/download/23.11.0-0/Miniforge3-23.11.0-0-MacOSX-arm64.sh

      - name: Install uxarray
        run: |
          python -m pip install . --no-deps

      - name: conda list
        run: |
          conda list

      - name: Run Namespace Tests
        run: |
          python -m pytest test

  link-check:
      if: github.event_name != 'pull_request'
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash -l {0}
      steps:
        - name: checkout
          uses: actions/checkout@v7

        - name: environment setup
          id: link-env-setup
          continue-on-error: true
          uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v2
          with:
            environment-file: ci/docs.yml
            cache-environment: true
            cache-environment-key: "linkcheck-${{env.TODAY}}"
            create-args: >-
              python=3.11

        - name: retry environment set up if failed
          if: steps.link-env-setup.outcome == 'failure'
          uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v2
          with:
            download-micromamba: false
            environment-file: ci/docs.yml
            cache-environment: true
            cache-environment-key: "linkcheck-${{env.TODAY}}"
            create-args: >-
              python=3.11

        - name: Install uxarray
          run: |
            python -m pip install . --no-deps

        - name: conda list
          run: |
            conda list

        - name: Make docs with linkcheck
          uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
          with:
            timeout_minutes: 20
            max_attempts: 3
            command: |
              eval "$(micromamba shell hook --shell bash)"
              micromamba activate uxarray-docs
              cd docs
              echo 'nb_execution_mode = "off"' >> conf.py
              make linkcheck

  test-optional-deps:
    # Ensures can install with various combinations of optional dependencies,
    # and that some corresponding tests pass or crash appropriately.
    # Just a single machine and single Python version should be good enough,
    # the goal here is to spot-check that optional deps work as expected,
    # not to run an exhaustive set of tests with each combination of deps.
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: setup-python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: no optional deps
        run: |
          python -m venv "$RUNNER_TEMP/venv-none"
          source "$RUNNER_TEMP/venv-none/bin/activate"
          python -m pip install "." pytest
          python -m pytest test_optional_deps/test_installed_with_no_opts.py

      - name: geo only
        run: |
          python -m venv "$RUNNER_TEMP/venv-geo"
          source "$RUNNER_TEMP/venv-geo/bin/activate"
          python -m pip install ".[geo]" pytest
          python -m pytest test_optional_deps/test_installed_with_geo.py

      - name: viz only
        run: |
          python -m venv "$RUNNER_TEMP/venv-viz"
          source "$RUNNER_TEMP/venv-viz/bin/activate"
          python -m pip install ".[viz]" pytest
          python -m pytest test_optional_deps/test_installed_with_viz.py

      - name: viz and geo
        run: |
          python -m venv "$RUNNER_TEMP/venv-viz_and_geo"
          source "$RUNNER_TEMP/venv-viz_and_geo/bin/activate"
          python -m pip install ".[viz,geo]" pytest
          python -m pytest test_optional_deps/test_installed_with_viz_and_geo.py
